# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01492f8ef2cb1677e293e48236650bf3d999a632872e9a2314b0a3e272043b8d4d11a55caeeb0068617bcd1b55e98ccc2431774ea80ac48ef632718b1f822837

test:
  secret_key_base: cc4ce7a11dfa5d39ccce6bbf7e47d18c3087fb3271c44edf73a327cf74bcd7ffd58649df50ac807325fdd9e9bc2ad2190ff652e98287faf4685b77ddc498f069

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
