require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JobListingsController do

  # This should return the minimal set of attributes required to create a valid
  # JobListing. As you add validations to JobListing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobListingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all job_listings as @job_listings" do
      job_listing = JobListing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:job_listings).should eq([job_listing])
    end
  end

  describe "GET show" do
    it "assigns the requested job_listing as @job_listing" do
      job_listing = JobListing.create! valid_attributes
      get :show, {:id => job_listing.to_param}, valid_session
      assigns(:job_listing).should eq(job_listing)
    end
  end

  describe "GET new" do
    it "assigns a new job_listing as @job_listing" do
      get :new, {}, valid_session
      assigns(:job_listing).should be_a_new(JobListing)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_listing as @job_listing" do
      job_listing = JobListing.create! valid_attributes
      get :edit, {:id => job_listing.to_param}, valid_session
      assigns(:job_listing).should eq(job_listing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JobListing" do
        expect {
          post :create, {:job_listing => valid_attributes}, valid_session
        }.to change(JobListing, :count).by(1)
      end

      it "assigns a newly created job_listing as @job_listing" do
        post :create, {:job_listing => valid_attributes}, valid_session
        assigns(:job_listing).should be_a(JobListing)
        assigns(:job_listing).should be_persisted
      end

      it "redirects to the created job_listing" do
        post :create, {:job_listing => valid_attributes}, valid_session
        response.should redirect_to(JobListing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_listing as @job_listing" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobListing.any_instance.stub(:save).and_return(false)
        post :create, {:job_listing => {  }}, valid_session
        assigns(:job_listing).should be_a_new(JobListing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobListing.any_instance.stub(:save).and_return(false)
        post :create, {:job_listing => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested job_listing" do
        job_listing = JobListing.create! valid_attributes
        # Assuming there are no other job_listings in the database, this
        # specifies that the JobListing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JobListing.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => job_listing.to_param, :job_listing => { "these" => "params" }}, valid_session
      end

      it "assigns the requested job_listing as @job_listing" do
        job_listing = JobListing.create! valid_attributes
        put :update, {:id => job_listing.to_param, :job_listing => valid_attributes}, valid_session
        assigns(:job_listing).should eq(job_listing)
      end

      it "redirects to the job_listing" do
        job_listing = JobListing.create! valid_attributes
        put :update, {:id => job_listing.to_param, :job_listing => valid_attributes}, valid_session
        response.should redirect_to(job_listing)
      end
    end

    describe "with invalid params" do
      it "assigns the job_listing as @job_listing" do
        job_listing = JobListing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobListing.any_instance.stub(:save).and_return(false)
        put :update, {:id => job_listing.to_param, :job_listing => {  }}, valid_session
        assigns(:job_listing).should eq(job_listing)
      end

      it "re-renders the 'edit' template" do
        job_listing = JobListing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobListing.any_instance.stub(:save).and_return(false)
        put :update, {:id => job_listing.to_param, :job_listing => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_listing" do
      job_listing = JobListing.create! valid_attributes
      expect {
        delete :destroy, {:id => job_listing.to_param}, valid_session
      }.to change(JobListing, :count).by(-1)
    end

    it "redirects to the job_listings list" do
      job_listing = JobListing.create! valid_attributes
      delete :destroy, {:id => job_listing.to_param}, valid_session
      response.should redirect_to(job_listings_url)
    end
  end

end
